README.md
_ci/publish-amis-in-new-account.md
examples/root-example/README.md
modules/consul-cluster/README.md

Previously, image links were still expressed as relative links. Now all markdown links use the full repo URL.

Convert relative image links to absolute image links per Terraform module official spec.

---

README.md
examples/consul-ami/README.md
examples/consul-examples-helper/consul-examples-helper.sh
modules/consul-cluster/README.md

1. The latest version of Consul uses `-http-addr` and not `rpc-addr`. Update the example script to use it.
1. Fix some minor issues in the READMEs.

Fix READMEs and bug in example startup script

---

main.tf
variables.tf

Adds the ability to optionally deploy the consul agents to a specified VPC.  The default behavior is still maintained, in that if `vpc_id` is not supplied, the default VPC is used.

ability to supply vpc_id

---

examples/root-example/README.md
modules/consul-cluster/README.md
modules/consul-iam-policies/README.md
modules/consul-security-group-rules/README.md

The official Terraform Module standard requires that files be named `variables.tf` instead of `vars.tf`. Looks like we forgot to update some of these links. Fixes #26

Fix outdated links to vars.tf

---

.gitignore
examples/consul-ami/README.md
modules/install-consul/install-consul

Should fix the symlink issues for people.  Does it both directions and then fails the script if it can't find supervisorctl/supervisord

Fixed symlink issues on CentOS

---

main.tf
modules/consul-cluster/main.tf
modules/consul-cluster/variables.tf

This PR adds a new variable `tags` to pass in extra tag blocks for the autoscaling group, and via tag propagation (if enabled) also to the instances.
My use case is building a complete environment of which a consul cluster is part. All resources in that environment need to be tagged with custom tags. Examples of such tags are the name of the environment and a flag to determine if monitoring should be enabled on those resources.
I've tested this PR using test-kitchen and awspec.
I've specified tags like this:
```hcl
module "consul_cluster" {
source = "github.com/miguelaferreira/terraform-aws-consul//modules/consul-cluster?ref=extra-tags"
...
tags = [
{
key                 = "Project"
value               = "${var.project}"
propagate_at_launch = true
},
{
key                 = "Environment" …
```

Add tags variable to allow passing in extra tags

---

modules/consul-cluster/main.tf

This PR reuses the `cluter_name` variable to set `name_prefix` on the cluster autoscaling group resource. 
As the documentation mentions, the `cluster_name` should be "*used to namespace all resources created by this module*".
I've tested this PR with test-ktichen and awspec. I've defined the name of the cluster like this:
```hcl
module "consul_cluster" {
source = "github.com/miguelaferreira/terraform-aws-consul//modules/consul-cluster?ref=namespace-autoscaling-group"
cluster_name = "ProjectTestConsul"
...
}
```
I wrote a awspec test like this:
```ruby
require 'awspec'
require 'rubygems'
tf_output = eval(ENV['KITCHEN_KITCHEN_TERRAFORM_OUTPUT'])
consul_autoscaling_group_name = tf_output[:consul_autoscaling_group_name][:value]
describe consul_autoscaling_group_name do
it { should start_with …
```

Use variable cluster_name as a name prefix for the autoscaling group

---

modules/run-consul/README.md
modules/run-consul/run-consul

This PR adds the ability to specify a datacenter field in the Consul config. As it exists now, the datacenter is set to the AWS region name. In our situation, we can have multiple deployments in the same region (staging vs. production).
A `--datacenter` option has been added to the run-consul script. It is optional and defaults to the old behavior of using the AWS region.
**Downtime needed:** No.
This change does not require downtime. New nodes can be swapped in with this change and there are no adverse effects. Specifying a different datacenter may require downtime, but it is the same as-if changing the datacenter manually.
**Backwards compatible:** Yes.
The default behavior without the option is to use the region name, which is identical to what it was before the change.
The change was …

Specify custom datacenter in run-consul script

---

modules/consul-cluster/main.tf

When using this module to create a stand alone Consul cluster, it is
helpful to be able to use a data source to import the SG in order to
configure other modules. e.g. a separate Nomad cluster module with its 
own TF state to add an SG rule to allow the Nomad clients, also Consul 
clients, to talk to the main Consul server SG.
Because we only give a name_prefix to this SG group currently, there is 
no way to use a data source to import based on name. Passing around
terraform outputs for this type of thing is a faff due to setup and
separate state.

Add Name tag to Consul Security Group

---

README.md
modules/consul-client-security-group-rules/README.md
modules/consul-client-security-group-rules/main.tf
modules/consul-client-security-group-rules/variables.tf
modules/consul-security-group-rules/main.tf

When deploying consul as an agent on, say a Vault cluster, I needed a set of rules to permit the LAN gossip traffic. This simple module permits that inbound traffic. Relates to https://github.com/hashicorp/terraform-aws-vault/pull/56

Add simple sg rules for consul agents

---

examples/consul-ami/README.md

Amazon Linux does not have Git installed by default. The first provisioner step makes sure we install it. `|| true` is used for compatibility with Ubuntu-based builder which does not have `yum` package manager.
Otherwise Amazon Linux will fail with:
==> amazon-linux-ami: Provisioning with shell script: /var/folders/zr/k8_fxx5d1xx56n1m758byg4r0000gn/T/packer-shell218591116
amazon-linux-ami: /tmp/script_3975.sh: line 2: git: command not found
==> amazon-linux-ami: Terminating the source AWS instance...

Install Git on Amazon Linux

---

examples/example-with-encryption/main.tf
examples/example-with-encryption/outputs.tf
examples/example-with-encryption/variables.tf
examples/root-example/README.md
main.tf
outputs.tf
test/Gopkg.lock
test/Gopkg.toml
test/consul_helpers.go
variables.tf

Fixes #49. 
I’m removing the `provider` block and `aws_region` variable from the examples in this repo so that they work properly with the instructions you get from the auto-generated docs on the [Terraform Registry page](https://registry.terraform.io/modules/hashicorp/consul/aws/0.3.3) for this module:
```hcl
module "consul" {
source  = "hashicorp/consul/aws"
version = "0.3.3"
}
```

Remove provider and aws_region from examples

---

modules/run-consul/run-consul
test/consul_helpers.go

To allow arbitrary environment variables to be used with Consul agent.
In particular, this is to enable the use of the new [beta UI](https://github.com/hashicorp/consul/pull/4086) by setting the environment variable `CONSUL_UI_BETA`. 
I have tested it with my setup and the environment variable is successfully passed to the Consul agent started by supervisord.

Add environment variables to supervisord config

---

examples/consul-ami/README.md
examples/consul-ami/consul.json
modules/install-consul/README.md
modules/install-consul/install-consul

* Allows passing an exact download url to the packer ami template and the install script. 
* Bumps the default consul version in the ami
@infosecgithub

Allow enterprise install

---

README.md
_ci/publish-amis-in-new-account.md
_ci/publish-amis.sh
_docs/amazon-linux-ami-list.md
_docs/ubuntu16-ami-list.md
circle.yml
examples/consul-ami/consul.json

In #77 I tried to simplify how we publish AMIs. While the code worked fine from my computer, it unfortunately would hang or pause for long periods of time in CircleCI with no log output, and the build would be terminated with the error "command XXX took more than 10 minutes since last output" (example: https://circleci.com/gh/hashicorp/terraform-aws-consul/89). 
I'm sure there's a way to work around this, but I don't have any more time to pour into this, so I'm reverting to the original AMI publishing code, and copying over just the credentials fix.

Revert ami publishing changes

---

modules/run-consul/run-consul

* Allows overwriting of autopilot settings on `run-consul`
* Some formatting fixes on usage text
@infosecgithub
@bgt101

Allow overwriting Autopilot configuration

---

examples/example-with-custom-asg-role/main.tf
examples/example-with-custom-asg-role/variables.tf
test/consul_cluster_with_custom_asg_role_test.go
test/consul_helpers.go

* Test did not account for the role already existing
* Adds timestamp to role name to make unique
* Due to limits in the AWS role name length the uuid function won't work
* Due to limits in the AWS role name supported characters it has to do
some funky replace statements on the timestamp

Fix broken test for custom ASG service-linked role

---

modules/consul-cluster/README.md
modules/consul-cluster/main.tf
modules/consul-cluster/outputs.tf
modules/consul-cluster/variables.tf
modules/consul-iam-policies/main.tf
modules/consul-iam-policies/variables.tf

Please review my PR that allows the IAM role and policy creation to be disabled.  This allows the role to be created externally and the ARN of the role to be supplied via tf variable.
This helps in situations where end users roles might not have the right to modify IAM but have the rights to deploy standard compute resources.
ref:
https://github.com/hashicorp/terraform-aws-consul/issues/42
I am afraid i am not very good with go so have not updated the tests but i am not in a situation currently where i can test with IAM enabled anyway so if someone could please confirm that all is good with this and merge it in, if not then please let me know.

Switchable IAM

---

modules/consul-cluster/main.tf
modules/consul-cluster/variables.tf

Address the error:
Error: Error running plan: 1 error(s) occurred:
* module.consul-servers.aws_security_group_rule.allow_ssh_inbound_from_security_group_ids: aws_security_group_rule.allow_ssh_inbound_from_security_group_ids: value of 'count' cannot be computed
This is a known limitation of the Terraform API. Hard-coding the value is the only currently available solution.

Add parameter for specifying count of allowed_ssh_security_group_ids

---

.circleci/config.yml
_ci/publish-amis.sh

It works as seen on https://circleci.com/gh/hashicorp/terraform-aws-consul/tree/publish-amis
Additionally, "gruntwork-ci" github user needed access to this repo so it could publish the markdown with the resulting amis

Fix ami publishing and add nightly builds

---

examples/example-with-encryption/README.md

Noticed a typo when going through the README

Fix minor typo in example-with-encryption README

---

examples/consul-ami/consul.json
examples/example-with-encryption/packer/consul-with-certs.json

We are getting `Error creating AMI: InvalidAMIName.Duplicate: AMI name consul-ubuntu-2019-03-29T12-28-48Z is already in use by AMI ami-0f589d96558469b10` style errors in tests. Hopefully this will fix it.

Add UUID to AMI names

---

modules/run-consul/run-consul

To make sure that consul service will automatically start after a server reboot it has to be enabled so that systemd will know to autostart it during boot sequence.

Enable systemd consul service

---

examples/consul-ami/consul.json

Nightly builds started flagging 13 days ago that all amazon linux tests were failing
This was the culprit

Prevent packer from catching SQL server specific ami

---

modules/run-consul/run-consul

In order to be able to add recursors servers to consul config (https://www.consul.io/docs/agent/options.html#recursors) a new parameter needs to be added to run-consul script.
It is useful when you also install dnsmasq and want to recursively resolve queries that are not inside the consul service domain.
Another example could be if you want to access a private EKS API endpoint from an on-premise network connected through AWS Direct Connect (DX) or a virtual private network (VPN) to EKS VPC.

Add --recursor option for run-consul script

---

modules/run-consul/run-consul

Hey there- thanks for this module!
We've been noticing a race condition wherein our application, which depends on having joined the Consul cluster, starts up _after_ Consul has started but _before_ the cluster has been joined. 
We are using systemd service configurations for both Consul and our application, which explicitly defines `Requires=consul.service` and `After=consul.service`. Because the `consul.service` Unit file written by this module has no Type specified, it defaults to `simple`, so systemd considers the service "active (running)" as soon as the task is started.
I saw [this PR on the Consul library](https://github.com/hashicorp/consul/pull/5689) itself, and thought that this module probably wants to be updated too, since others (like us) are using this to configure remote …

Specify Type notify on systemd service

---

README.md
examples/consul-ami/README.md
examples/consul-ami/consul.json
examples/example-with-encryption/packer/consul-with-certs.json
modules/install-consul/README.md
modules/install-consul/install-consul
modules/run-consul/README.md
modules/setup-systemd-resolved/README.md
modules/setup-systemd-resolved/setup-systemd-resolved
test/consul_cluster_test.go
test/consul_cluster_with_custom_asg_role_test.go
test/consul_cluster_with_encryption_test.go
test/consul_enterprise_test.go
test/consul_helpers.go

Ubuntu 18.04 Support

---

modules/run-consul/run-consul

After #146, systemd now waits for consul's notification of having joined the cluster before signaling that the service is alive. This however may occasionally result in larger waiting times and intermittent timeout failures.
The following error was observed in the [terraform-aws-vault](https://github.com/hashicorp/terraform-aws-vault) logs: `Job for consul.service failed because a timeout was exceeded. See "systemctl status consul.service" and "journalctl -xe" for details.`
As a remedy, this PR raises the timeout from 90s (the default) to a more reasonable 300s.

Increase timeout on systemd config

---

modules/consul-client-security-group-rules/variables.tf
modules/consul-security-group-rules/variables.tf

These variables don't necessarily have to be set to anything and leaving
them empty can work just fine due to the security groups allowing
"self".  As such setting them to an empty list avoids extra rules being
put in place.

Set defaults for allowed_inbound_cidr_blocks

---

modules/consul-cluster/README.md

Fix missing specification of value that enables auto-discovery of peers by EC2 tags

Missing argument in example user data that prevents auto-discovery of server peers

---

examples/consul-ami/consul.json

This fixes the AMI example so that dnsmasq installation step is skipped for Ubuntu 18.

Don't install dnsmasq on ubuntu18

---

modules/consul-cluster/main.tf
modules/consul-cluster/variables.tf

This change solve issue: https://github.com/hashicorp/terraform-aws-consul/issues/177
The changes are tested with an existing consul-cluster without scale-in protection. The optional scale-in protection is set to true.
The terraform plan output is here:
https://gist.github.com/mawa-jnd/476ab6680a68d6c4b1770a372cfff5aa
The change is:
- backward compatible
- has no downtime with default setup as changing the ASG will not automatically restart instances

Add instance scale-in protection for consul-cluster

---

modules/consul-cluster/variables.tf

Related to [Issue 181](https://github.com/hashicorp/terraform-aws-consul/issues/181)
Newest `provider-aws` version only allows us to set one of the 2 variables: `availability_zones and subnet_ids` when creating AutoScalingGroups.
As per @brikis98 suggestion, I am changing the default value of these 2 variables to null so they're no longer conflicting, allowing to set either of them when using the `consul_cluster` module.

Edit default value for availability_zones and subnet_ids vars to null

---

modules/install-consul/install-consul
modules/install-dnsmasq/install-dnsmasq
modules/run-consul/run-consul

This resolves some of the obvious shellcheck warnings. There are still a few more, but they require a bit more digging to fully grasp what is being called out so I decided to leave them untouched.

Fix shellcheck warnings

---

modules/run-consul/run-consul

This adds support for enabling `verify_server_hostname` to `true` in the consul server configuration. This is a recommended setting for production consul servers to ensure that agents can't promote themselves to become a server using the client certificate key (if `verify_server_hostname` is `false`, then any certificate that is validated by the RPC CA can become a server).
See https://www.consul.io/docs/agent/options#verify_server_hostname for more info.

Add support for server hostname checks

---

modules/install-dnsmasq/README.md
modules/install-dnsmasq/install-dnsmasq

This pull request allows the configuration of the dnsmasq `listen-address`. Previously, the only way to modify this also modified the consul IP address that dnsmasq routed to. This is relatively backward compatible. Users of the default consul-ip default value will see the same behavior, as the dnsmasq listen-address defaults to the same value. However, if a user was running consul on a different IP, and ran dnsmasq on that same IP to accommodate this script, they will need to update their usage of this script.

Allow configuration of dnsmasq listen address separate from the consul IP address

---

.circleci/config.yml
.pre-commit-config.yaml
examples/example-with-custom-asg-role/main.tf
examples/example-with-encryption/main.tf
examples/example-with-encryption/packer/consul-with-certs.json
main.tf
modules/consul-client-security-group-rules/main.tf
modules/consul-cluster/main.tf
modules/consul-iam-policies/main.tf
modules/consul-security-group-rules/main.tf
test/aws_helpers.go
test/terratest_helpers.go

1. Update `required_version` to `0.12.26` everywhere.
1. Add pre-commit hooks.
1. Update version numbers in CI build.
1. Run `go fmt`.
1. Fix folder copy in a Packer template. Our previous Circle CI Docker image used to check out the repo into a folder called `terraform-aws-consul`, so the Packer template could use a `file` provisioner to copy it from that folder name. Our new Circle CI Docker image uses a different folder name (e.g., `project`), so we have to update the Packer template to work even if it doesn't know the folder name.
1. Add retries for Packer builds for what looks like a transient build failure.

Update repo to work with TF 0.13

---

.circleci/config.yml
_ci/publish-amis.sh

In https://github.com/hashicorp/terraform-aws-consul/pull/192, I updated the build to use a different Docker image, with a newer version of Go that doesn't rely on everything running in the `/go/xxx` path. Unfortunately, I forgot to update the deploy portion of the build, which publishes AMIs, and was still relying on those paths. This PR fixes the deploy step. I created a temporary, internal release to validate it, as the deploy step doesn't run on branches, by default: https://github.com/hashicorp/terraform-aws-consul/releases/tag/v0.8.1-internal-test

Fix deploy step in build

---

main.tf
modules/consul-cluster/main.tf
modules/consul-cluster/variables.tf
modules/consul-security-group-rules/main.tf
modules/consul-security-group-rules/variables.tf
variables.tf

PR addresses part of issue https://github.com/hashicorp/terraform-aws-consul/issues/92
Add security group for consul default https api port 8501.
https://www.consul.io/docs/install/ports

Add security group for consul default https api port 8501

---

main.tf

Avoiding this kind of warning
```
Warning: Interpolation-only expressions are deprecated
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.
```

Fixed interpolation deprecation warnings

---

modules/consul-cluster/main.tf
modules/consul-cluster/variables.tf

Provides flexibility to users for setting `permissions_boundary` to the created IAM role.
Defaults to `null` to preserve the same behavior as before.

Add `permissions_boundary` for created IAM role.

---

examples/consul-ami/consul.json
examples/example-with-custom-asg-role/main.tf
examples/example-with-custom-asg-role/outputs.tf
examples/example-with-custom-asg-role/variables.tf
examples/example-with-encryption/main.tf
examples/example-with-encryption/outputs.tf
examples/example-with-encryption/packer/consul-with-certs.json
examples/example-with-encryption/variables.tf
main.tf
modules/run-consul/run-consul
outputs.tf

* bump `min_packer_version` -> `1.5.4`
* bump `consul_version` -> `1.9.2`
* update consul service configuration
* Replace deprecated `ui` field by `ui_config` object: https://www.consul.io/docs/agent/options\#ui-1
* Add `telemetry { disable_compat_1.9 = true }` to disable metrics deprecated in `v1.9`: https://www.consul.io/docs/agent/options\#telemetry-disable_compat_1.9

Update agent configuration

---

test/consul_helpers.go

For more details see #208 and #209

Add more retries for entreprise test case

---

modules/install-consul/install-consul

The install-consul script now grants read and execute access to the directory where the Consul binary is installed. This fixes the issue reported under #210, while also allowing users who sign in under a different login to use the Consul binary for administrative purposes if necessary.

Fix for #210: can't find Consul binary when executing through Packer

---

NOTICE

This removes any ambiguity in the NOTICE as to how the code is licensed. Fixes #214.

Update NOTICE with license info

---

modules/consul-security-group-rules/main.tf

Received an error using the module in our terraform:
Error: One of ['cidr_blocks', 'ipv6_cidr_blocks', 'self', 'source_security_group_id', 'prefix_list_ids'] must be set to create an AWS Security Group Rule 
Error on .terraform/modules/consul_servers/modules/consul-security-group-rules/main.tf line 70, in resource "aws_security_group_rule" "allow_https_api_inbound": 
Error: resource "aws_security_group_rule" "allow_https_api_inbound" { 
If the module is given only security groups and not cidr ranges, a security group rule is created without all the necessary attributes.  Change applies the right boolean logic for this case.

Set up http_api access correctly

---

modules/install-consul/install-consul

- Include logic to determine binary architecture from returned value from `uname -m`
- Tested on a `c6g.*` EC2 instance running Amazon Linux 2
```sh
$ uname -m
aarch64
```
- Tested on a Raspberry Pi 3B running Raspbian
```sh
$ uname -m
armv7l
```
- Tested on some good 'ol `amd64` Linux
```sh
$ uname -m
x86_64
```

Update install-consul logic to determine CPU arch which makes it run on Graviton based EC2 instances

---

examples/example-with-custom-asg-role/main.tf
examples/example-with-encryption/main.tf
main.tf

The provider `template_file` is deprecated and it is encouraged to migrate to the built in `templatefile()` function.
As `template_file` is archived it also means that it's lacking builds for M1 macs.

Migrate to templatefile function from deprecated template_file provider.

---

examples/consul-examples-helper/consul-examples-helper.sh

this prevent the extra `"..."` quotes which messes up the `aws ec2 describe-instances` call

use `-raw` when getting values from `terraform output`
